before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: l0NFU7T/+cUREsIkRiTVzK+eXsn3lT/Dne2fLuqG3wEC39/FVY03VZHibeCWMy3D57DAk4pNkVfoQnhXqMqa4DJ+GLMx+PjqWEprWgGFlbST0YozmVJOErw0O7G3P8dCQWPOn6uk4Zd3O25z4UIlp+x9ewTxW6Z6hpaS3XRtlWhatoUtB/xwR1DAPXdUpVpXki/Jp5XsylrWb37hn9XCPdoN1TFbH8FB8zkjGd+hi/VjzmuVhN3xOFI+uDOgQVjKuS8cyDnnFUoJAZoT6eLSkQYoCY1alfoLyqkpmW5sWm2t59CDlBNf0/6AZpSlEWy30ef3u64rnL/5i6r1EptGOTNmK7rPK3pT7Vt+NdLbX4ZQhiHKxAWq8iNu75gfy9GWNNiHWQ/sHaAE+wG3cUTerr/mxzNx5hB2GwcOVQ90m60RtKRApjv+PNr3gawENcZVNCpu41Yq4ZgmJ5XY5E+5nwW6MVw9f+sjzvPezcQ3CXq7+xIAj3caV+e4GIGNOu9z/l8Ro5xO0FUmec4J9fYyRfJgy6maVR0uAhLyJBSlqLho8vZRSB3sKoFO0/Djn/kV9OvHmV1fxQVQIIaTqveP8RC92fies8J4hLRxWZSrpPFoWnQula3l6EF43ao2EjiBAOGssY/BR6H7/GxjI7+ZVNqm98eCxcf6AGIyKHshXSE= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
